/*
 * Copyright 2024-2026 Embabel Pty Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.embabel.vaadin.component;

import com.embabel.ux.form.*;
import com.vaadin.flow.component.Component;
import com.vaadin.flow.component.Key;
import com.vaadin.flow.component.ShortcutRegistration;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.checkbox.Checkbox;
import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.datepicker.DatePicker;
import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.html.Span;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.radiobutton.RadioButtonGroup;
import com.vaadin.flow.component.textfield.IntegerField;
import com.vaadin.flow.component.textfield.NumberField;
import com.vaadin.flow.component.textfield.TextArea;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.component.timepicker.TimePicker;

import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;
import java.util.function.Consumer;

/**
 * Renders an Embabel {@link Form} as Vaadin components.
 * Collects user input and produces a {@link FormSubmission} on submit.
 * <p>
 * This is a generic, reusable component — it works with any {@link Form}
 * generated by {@link SimpleFormGenerator} or hand-built.
 */
public class FormRenderer extends VerticalLayout {

    private final Form form;
    private final Map<String, ValueExtractor> extractors = new LinkedHashMap<>();

    /**
     * Create a form renderer for the given form model.
     *
     * @param form       the UX-independent form definition
     * @param onSubmit   callback invoked with the collected {@link FormSubmission}
     */
    private ShortcutRegistration escapeShortcut;

    /**
     * Create a form renderer with submit and dismiss support.
     *
     * @param form       the UX-independent form definition
     * @param onSubmit   callback invoked with the collected {@link FormSubmission}
     * @param onDismiss  callback invoked when the user dismisses the form (may be null)
     */
    public FormRenderer(Form form, Consumer<FormSubmission> onSubmit, Runnable onDismiss) {
        this.form = form;
        setPadding(true);
        setSpacing(true);
        addClassName("awaitable-form");

        add(new H3(form.getTitle()));

        for (Control control : form.getControls()) {
            if (control instanceof com.embabel.ux.form.Button buttonDef) {
                var submitButton = new Button(buttonDef.getLabel());
                submitButton.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
                submitButton.addClassName("awaitable-form-submit");

                var dismissButton = new Button("Dismiss");
                dismissButton.addThemeVariants(ButtonVariant.LUMO_TERTIARY);
                dismissButton.addClassName("awaitable-form-dismiss");

                submitButton.addClickListener(e -> {
                    submitButton.setEnabled(false);
                    dismissButton.setEnabled(false);
                    var submission = collectSubmission();
                    onSubmit.accept(submission);
                    removeEscapeShortcut();
                });

                dismissButton.addClickListener(e -> dismiss(onDismiss));

                var buttons = new HorizontalLayout(submitButton, dismissButton);
                buttons.setSpacing(true);
                add(buttons);
            } else {
                var component = renderControl(control);
                if (component != null) {
                    add(component);
                }
            }
        }

        // Escape key dismisses the form
        addAttachListener(e ->
            escapeShortcut = e.getUI().addShortcutListener(
                event -> dismiss(onDismiss), Key.ESCAPE
            )
        );
        addDetachListener(e -> removeEscapeShortcut());
    }

    /**
     * Create a form renderer (back-compatible constructor without dismiss).
     */
    public FormRenderer(Form form, Consumer<FormSubmission> onSubmit) {
        this(form, onSubmit, null);
    }

    private void dismiss(Runnable onDismiss) {
        removeEscapeShortcut();
        removeAll();
        var badge = new Span("Dismissed");
        badge.addClassName("awaitable-outcome-rejected");
        add(badge);
        if (onDismiss != null) {
            onDismiss.run();
        }
    }

    private void removeEscapeShortcut() {
        if (escapeShortcut != null) {
            escapeShortcut.remove();
            escapeShortcut = null;
        }
    }

    private Component renderControl(Control control) {
        if (control instanceof com.embabel.ux.form.TextField tf) {
            return renderTextField(tf);
        } else if (control instanceof com.embabel.ux.form.TextArea ta) {
            return renderTextArea(ta);
        } else if (control instanceof com.embabel.ux.form.Checkbox cb) {
            return renderCheckbox(cb);
        } else if (control instanceof Dropdown dd) {
            return renderDropdown(dd);
        } else if (control instanceof RadioGroup rg) {
            return renderRadioGroup(rg);
        } else if (control instanceof com.embabel.ux.form.DatePicker dp) {
            return renderDatePicker(dp);
        } else if (control instanceof com.embabel.ux.form.TimePicker tp) {
            return renderTimePicker(tp);
        } else if (control instanceof Slider sl) {
            return renderSlider(sl);
        } else if (control instanceof Toggle tg) {
            return renderToggle(tg);
        }
        return null;
    }

    private Component renderTextField(com.embabel.ux.form.TextField def) {
        // Detect integer pattern to use IntegerField
        if ("^\\d+$".equals(def.getValidationPattern())) {
            var field = new IntegerField(def.getLabel());
            field.setPlaceholder(def.getPlaceholder());
            field.setRequiredIndicatorVisible(def.getRequired());
            field.setReadOnly(def.getDisabled());
            if (!def.getValue().isEmpty()) {
                try {
                    field.setValue(Integer.parseInt(def.getValue()));
                } catch (NumberFormatException ignored) {
                }
            }
            field.setWidthFull();
            extractors.put(def.getId(), () -> {
                var v = field.getValue();
                return v != null ? new ControlValue.TextValue(v.toString()) : ControlValue.EmptyValue.INSTANCE;
            });
            return field;
        }

        var field = new TextField(def.getLabel());
        field.setPlaceholder(def.getPlaceholder());
        field.setValue(def.getValue());
        field.setRequiredIndicatorVisible(def.getRequired());
        field.setReadOnly(def.getDisabled());
        if (def.getMaxLength() != null) {
            field.setMaxLength(def.getMaxLength());
        }
        field.setWidthFull();
        extractors.put(def.getId(), () -> new ControlValue.TextValue(field.getValue()));
        return field;
    }

    private Component renderTextArea(com.embabel.ux.form.TextArea def) {
        var area = new TextArea(def.getLabel());
        area.setPlaceholder(def.getPlaceholder());
        area.setValue(def.getValue());
        area.setRequiredIndicatorVisible(def.getRequired());
        area.setReadOnly(def.getDisabled());
        if (def.getMaxLength() != null) {
            area.setMaxLength(def.getMaxLength());
        }
        area.setWidthFull();
        extractors.put(def.getId(), () -> new ControlValue.TextValue(area.getValue()));
        return area;
    }

    private Component renderCheckbox(com.embabel.ux.form.Checkbox def) {
        var cb = new Checkbox(def.getLabel());
        cb.setValue(def.getChecked());
        cb.setReadOnly(def.getDisabled());
        extractors.put(def.getId(), () -> new ControlValue.BooleanValue(cb.getValue()));
        return cb;
    }

    private Component renderDropdown(Dropdown def) {
        var combo = new ComboBox<String>(def.getLabel());
        var labels = def.getOptions().stream().map(DropdownOption::getLabel).toList();
        combo.setItems(labels);
        combo.setPlaceholder(def.getPlaceholder());
        combo.setRequiredIndicatorVisible(def.getRequired());
        combo.setReadOnly(def.getDisabled());
        combo.setWidthFull();
        extractors.put(def.getId(), () -> {
            var v = combo.getValue();
            return v != null ? new ControlValue.OptionValue(v) : ControlValue.EmptyValue.INSTANCE;
        });
        return combo;
    }

    private Component renderRadioGroup(RadioGroup def) {
        var group = new RadioButtonGroup<String>();
        group.setLabel(def.getLabel());
        var labels = def.getOptions().stream().map(RadioOption::getLabel).toList();
        group.setItems(labels);
        if (def.getSelectedValue() != null) {
            group.setValue(def.getSelectedValue());
        }
        group.setReadOnly(def.getDisabled());
        extractors.put(def.getId(), () -> {
            var v = group.getValue();
            return v != null ? new ControlValue.OptionValue(v) : ControlValue.EmptyValue.INSTANCE;
        });
        return group;
    }

    private Component renderDatePicker(com.embabel.ux.form.DatePicker def) {
        var picker = new DatePicker(def.getLabel());
        if (def.getValue() != null) {
            picker.setValue(LocalDate.parse(def.getValue()));
        }
        picker.setRequiredIndicatorVisible(def.getRequired());
        picker.setReadOnly(def.getDisabled());
        picker.setWidthFull();
        extractors.put(def.getId(), () -> {
            var v = picker.getValue();
            return v != null ? new ControlValue.DateValue(v) : ControlValue.EmptyValue.INSTANCE;
        });
        return picker;
    }

    private Component renderTimePicker(com.embabel.ux.form.TimePicker def) {
        var picker = new TimePicker(def.getLabel());
        if (def.getValue() != null) {
            picker.setValue(LocalTime.parse(def.getValue()));
        }
        picker.setRequiredIndicatorVisible(def.getRequired());
        picker.setReadOnly(def.getDisabled());
        picker.setWidthFull();
        extractors.put(def.getId(), () -> {
            var v = picker.getValue();
            return v != null ? new ControlValue.TimeValue(v) : ControlValue.EmptyValue.INSTANCE;
        });
        return picker;
    }

    private Component renderSlider(Slider def) {
        // Vaadin doesn't have a native slider; use NumberField
        var field = new NumberField(def.getLabel());
        field.setMin(def.getMin());
        field.setMax(def.getMax());
        field.setStep(def.getStep());
        field.setValue(def.getValue());
        field.setReadOnly(def.getDisabled());
        field.setWidthFull();
        extractors.put(def.getId(), () -> {
            var v = field.getValue();
            return v != null ? new ControlValue.NumberValue(v) : ControlValue.EmptyValue.INSTANCE;
        });
        return field;
    }

    private Component renderToggle(Toggle def) {
        var cb = new Checkbox(def.getLabel());
        cb.setValue(def.getEnabled());
        cb.setReadOnly(def.getDisabled());
        extractors.put(def.getId(), () -> new ControlValue.BooleanValue(cb.getValue()));
        return cb;
    }

    /**
     * Collect all control values into a {@link FormSubmission}.
     */
    private FormSubmission collectSubmission() {
        Map<String, Object> values = new LinkedHashMap<>();
        for (var entry : extractors.entrySet()) {
            var controlValue = entry.getValue().extract();
            values.put(entry.getKey(), toRawValue(controlValue));
        }
        return new FormSubmission(form.getId(), values, UUID.randomUUID().toString(), Instant.now());
    }

    /**
     * Convert a {@link ControlValue} to its raw Java value for the submission map.
     */
    private static Object toRawValue(ControlValue cv) {
        if (cv instanceof ControlValue.TextValue tv) return tv.getValue();
        if (cv instanceof ControlValue.BooleanValue bv) return bv.getValue();
        if (cv instanceof ControlValue.NumberValue nv) return nv.getValue();
        if (cv instanceof ControlValue.DateValue dv) return dv.getValue().toString();
        if (cv instanceof ControlValue.TimeValue tv) return tv.getValue().toString();
        if (cv instanceof ControlValue.OptionValue ov) return ov.getValue();
        if (cv instanceof ControlValue.MultiOptionValue mov) return mov.getValues();
        if (cv instanceof ControlValue.FileValue fv) return fv.getFileIds();
        return "";
    }

    @FunctionalInterface
    private interface ValueExtractor {
        ControlValue extract();
    }
}
